# Generated by Django 5.0.7 on 2024-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('teachers_id', models.PositiveSmallIntegerField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('subject_specialization', models.CharField(max_length=28)),
                ('years_of_experience', models.IntegerField()),
                ('office_hours', models.IntegerField()),
                ('biography', models.TextField(max_length=50)),
                ('course_taught', models.CharField(max_length=20)),
            ],
        ),
    ]
