# Generated by Django 5.0.7 on 2024-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('course', models.TextField()),
                ('class_teacher', models.TextField()),
                ('class_room', models.TextField()),
                ('day_of_the_week', models.TextField()),
            ],
        ),
    ]
